name: pdf_viewer
description: A flutter plugin for handling PDF files. Works on both Android & iOS
version: 1.0.7
homepage: https://github.com/SiroDaves

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  numberpicker: ^2.1.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sirodaves.pdf_viewer
        pluginClass: PdfViewerPlugin
      ios:
        pluginClass: PdfViewerPlugin
